export const QuizCulture = [
  {
    fournisseur: "Hugo Walandowitsch",
    quizz: {
      debutant: [
        {
          id: 0,
          question:
            "Dans quelle articulation du corps humain se situe la rotule ?",
          options: ["Le coude", "Le cou", "Le bassin", "Le genou"],
          answer: "Le genou",
          info: "Os plat situé à la partie antérieure du genou.",
          img: "https://www.larousse.fr/encyclopedie/data/images/1002104-Rotule.jpg",
        },
        {
          id: 1,
          question:
            "Combien de canines comporte la denture d'un homme adulte ?",
          options: [4, 6, 8, 10],
          answer: 4,
          info: "Les adultes ont plus de dents que les enfants; la plupart des adultes ont 32 dents. On compte parmi ces dents 8 incisives, 4 canines, 8 prémolaires et 12 molaires (dont 4 dents de sagesse).",
          img: "https://uploads.unify.uno/content/2022/9/24/1666615799107.gif",
          heroid: 1,
        },
        {
          id: 2,
          question:
            "Quel verbe est utilisé pour désigner le cri des dauphins ?",
          options: ["Gazouiller", "Glapir", "Siffler", "Chanter"],
          answer: "Siffler",
          info: "Les dauphins sont des mammifères et, en tant que tels, ils produisent des sons en faisant passer de l’air à travers le larynx dans la gorge. Les clics, gloussements, couinements et sifflements sont les cris du dauphin.",
          img: "https://media2.giphy.com/media/kMdlyJ74u9khW/giphy.gif?cid=ecf05e479t7a94dujlte1g429p8sedy2n3go2tg9c2mqu9ct&ep=v1_gifs_search&rid=giphy.gif&ct=g",
          heroid: 2,
        },
        {
          id: 3,
          question: "En quelle année est sorti le premier jeu vidéo ?",
          options: [1990, 1986, 1980, 1972],
          answer: 1972,
          info: "Le jeu vidéo est né dans les années 1970 et celui-ci ne cesse d'évoluer. Il est constitué d'images animées dans une interface, d'un gameplay accompagné de sons . Le premier jeu vidéo {Pong}, destiné au grand public est sorti en 1972. Au départ un simple bouton permettait de déplacer une raquette ou un personnage.",
          img: "https://media2.giphy.com/media/aTGwuEFyg6d8c/giphy.gif?cid=ecf05e47xcwt5uzieqcgzpohm40g8aooqo3uwol00ahmxnjz&ep=v1_gifs_search&rid=giphy.gif&ct=g",
          heroid: 3,
        },
        {
          id: 4,
          question: "Combien d'arêtes y a-t-il a un cube ?",
          options: [16, 8, 10, 12],
          answer: 12,
          info: "Le cube est un solide. Il est composé de 6 faces carrées, de 12 arêtes et de 6 sommets.",
          img: "https://static.techno-science.net/illustration/Definitions/1200px/h/hexahedron_36e44f6102cc4bf7856394f15763e2d3.gif",
          heroid: 4,
        },
        {
          id: 5,
          question:
            "Quel est le taux d'alcool à ne pas dépasser pour prendre le volant ? (Conducteur ordinaires)",
          options: [
            "0,2 par litre de sang",
            "0,5g par litre de sang",
            "0,75g par litre de sang",
            "1g par litre de sang",
          ],
          answer: "0,5g par litre de sang",
          info: "Selon le code de la route, le taux d'alcool maximal autorisé est de 0,5 g/L de sang, ce qui équivaut à 0,25 mg d'alcool par litre d'air expiré.",
          img: "https://www.drivecase.fr/conseils-prevention/wp-content/uploads/2021/01/ethylotest-ballon-ou-sans-ballon-scaled.jpeg",
          heroid: 5,
        },
        {
          id: 6,
          question: "Quelle est la hauteur totale de la Tour Eiffel ?",
          options: ["285m", "330m", "362m", "420m"],
          answer: "330m",
          info: "La Tour Eiffel, achevée en 1889 pour l'Exposition universelle de Paris, a été conçue par Gustave Eiffel. Initialement, elle mesurait 300 mètres de hauteur, mais avec l'ajout d'antennes, sa hauteur totale est maintenant d'environ 330 mètres. Au fil du temps, elle a subi plusieurs modifications avant d'atteindre sa hauteur actuelle, devenant ainsi l'une des structures les plus emblématiques du monde.",
          img: "https://media2.giphy.com/media/4JdDIsOorfa5xwSdje/giphy.gif?cid=ecf05e47eljxl0tfckmrbzw15o363qqfpua7oxcog606bwb9&ep=v1_gifs_search&rid=giphy.gif&ct=g",
          heroid: 6,
        },
        {
          id: 7,
          question:
            "Quel est le joueur de League of legends ayant gagné le plus de fois les Worlds ?",
          options: ["Faker", "Rookie", "Uzi", "Rekkles"],
          answer: "Faker",
          info: "Lee Sang-hyeok (en coréen 이상혁), connu sous le pseudonyme de Faker, est un joueur professionnel sud-coréen de League of Legends né le 7 mai 1996. Il est recruté par SK Telecom en 2013 et est actuellement midlaner pour l'équipe T1. Il est connu pour ses talents sur League of Legends et est considéré par beaucoup comme le meilleur joueur de tous les temps. Il est le seul joueur à avoir gagné quatre fois le Championnat du monde de League of Legends (2013, 2015, 2016 et 2023). Ses récompenses s`élèvent à 1 470 490.14 $, ce qui le classe 76e1 de tous les joueurs d'esport en termes de revenus.",
          img: "https://media2.giphy.com/media/v1.Y2lkPTc5MGI3NjExZmNuZHc3ODQ1N2MzbWFkNXI1M3A2eGtmMGpmZWhsM3IzazJjdDFscSZlcD12MV9pbnRlcm5hbF9naWZfYnlfaWQmY3Q9Zw/26Ec7TKFZ9XED3MM8/giphy.gif",
          heroid: 7,
        },
        {
          id: 8,
          question: "En quelle année le mur de Berlin a-t-il été construit ?",
          options: [1945, 1950, 1957, 1961],
          answer: 1961,
          info: "Dans la nuit du 12 au 13 août 1961 est érigé en plein Berlin ce qui deviendra l'un des symboles physiques de la Guerre froide : le mur de Berlin. Pendant presque trente ans c'est non seulement la capitale allemande, mais le pays, l'Europe et le monde lui-même que va scinder en deux le “Berliner Mauer”.",
          img: "https://t0.gstatic.com/licensed-image?q=tbn:ANd9GcREbNIoCdC8qGrmxpgsvM6sQHVGZlBASrgpOS7v2Rrqh-NCetdgOQWv8tJ13FlqneMM",
          heroid: 8,
        },
        {
          id: 9,
          question: "Lequel de ces pays ne paye pas en Euro ?",
          options: ["Norvège", "Grèce", "Chypre", "Andorre"],
          answer: "Norvège",
          info: "La procédure d'adhésion de la Norvège à l'Union européenne est une des trois procédures (avec celles de la Suisse et de l'Islande) qui n'ont pas abouti. Par deux fois, en 1972 et 1994 par voie référendaire, le peuple norvégien a refusé l'adhésion du pays à l'Union européenne.",
          img: "https://www.mon-drapeau.com/wp-content/uploads/2021/10/norvege.jpg",
          heroid: 9,
        },
      ],
      confirme: [
        {
          id: 10,
          question:
            "En quelle matière sont conçus les billets de banque en euros ?",
          options: ["Coton", "Polypropylène", "Ramie", "Bambou"],
          answer: "Coton",
          info: "Comme ceux de la première série, les billets en euros de la série « Europe » sont imprimés sur du papier à base de fibres de pur coton, ce qui leur donne cette sonorité craquante particulière et une meilleure résistance à l'usure.",
          img: "https://static.cnews.fr/sites/default/files/20euro_ecb_produktions_p1070898.jpg",
          heroid: 10,
        },
        {
          id: 11,
          question: "Quelle est la plus grande île de la Méditerranée ?",
          options: ["La Sicile", "Chypre", "La Sardaigne", "La Corse"],
          answer: "La Sicile",
          info: "Avec une superficie d`un peu plus de 25 000 kilomètres carrés elle est la plus grande île présente en mer Méditerranée, bien plus étendue par exemple que Malte, que la Sardaigne ou que la Corse. Sur cette île volcanique se trouve le plus haut volcan d`Europe et par conséquent aussi le plus haut sommet de Sicile. C`est le mythique Etna qui s`élève à 3 350 mètres d`altitude.",
          img: "https://images.partir.com/X33J-w8P5H4wQATgE_dLKH6S1Is=/1920x/panoramique/mobile/sicile.jpg",
          heroid: 11,
        },
        {
          id: 12,
          question:
            "Quel est le nom donné à un conducteur de traîneau à chien ?",
          options: ["Dog keeper", "Skipper", "Garrot", "Musher"],
          answer: "Musher",
          info: "On appelle musher la personne qui conduit un traîneau à neige tiré par un attelage de chiens. Il est également appelé meneur de chiens ou pilote d'attelage.",
          img: "https://upload.chien.com/img_global/24-activites/_light-777-les-courses-de-chiens-de-traineau.jpg",
          heroid: 12,
        },
        {
          id: 13,
          question: "Quelle est la formule du diamètre d'un cercle ?",
          options: ["2π x rayon", "π x rayon²", "rayon² + π", "2 x rayon"],
          answer: "2 x rayon",
          info: "Le rayon étant la distance du centre au bord du cercle, le diamètre est égal à deux fois le rayon, le diamètre étant la distance entre deux points du cercle en passant par le centre ",
          img: "https://media0.giphy.com/media/RH6kQ1MWCjMX48Sy3o/giphy.gif?cid=ecf05e47w8fmerhcpozx5rpv133gf5oix6k2w0fy9hpzegeh&ep=v1_gifs_search&rid=giphy.gif&ct=g",
          heroid: 13,
        },
        {
          id: 14,
          question: "Par quels pays passe le Rhône ?",
          options: [
            "France et Belgique",
            "France et Italie",
            "France et Suisse",
            "France et Allemagne",
          ],
          answer: "France et Suisse",
          info: "Le bassin versant du Rhône est situé sur deux pays : la Suisse et la France. Il mesure en tout 97 800 km2 , dont 90 000 km2 en France, soit environ 17 % de la superficie de la France métropolitaine, et 7 800 km2 en Suisse, soit 18,89 % de la superficie de la Suisse.",
          img: "https://www.lerhone.org/wp-content/themes/lerhone/dist/imgs/SVG/map.svg",
          heroid: 14,
        },
        {
          id: 15,
          question:
            "De quelle couleur est généralement le drapeau des arbitres de touches au foot ?",
          options: [
            "Jaune et Noir",
            "Rouge et Jaune",
            "Bleu et rouge",
            "Noir et Blanc",
          ],
          answer: "Rouge et Jaune",
          info: "Une paire de drapeau de touche de couleur jaune et rouge avec une poignet en plastique. Poignée ergonomique pour meilleure préhension. Conçu pour aider les arbitres à signaler les sorties de touche et hors jeux.",
          img: "https://imgresizer.eurosport.com/unsafe/1200x0/filters:format(jpeg)/origin-imgresizer.eurosport.com/2017/01/20/2006843-42132347-2560-1440.jpg",
          heroid: 15,
        },
        {
          id: 16,
          question: "Quel est le nom du chanteur du groupe Imagine Dragons ?",
          options: [
            "Dan Reynolds",
            "Andrew Tolman",
            "Wayne Sermon",
            "Ben Mckee",
          ],
          answer: "Dan Reynolds",
          info: "Imagine Dragons est un groupe de pop rock américain, originaire de Las Vegas dans le Nevada, et formé en 2008.Avec cinq albums au total, le groupe totalise 74 millions d`albums vendus et 160 milliards de streams dans le monde entier13. Remportant trois American Music Awards, dix Billboard Music Awards, et un Grammy Award, Imagine Dragons est devenu l`un des groupes de pop-rock les plus emblématiques de cette dernière décennie14. Dan Reynolds étant le chanteur.",
          img: "https://media4.giphy.com/media/xUPGchoqo8F5aUsP0k/giphy.gif?cid=ecf05e4721xelsfd3v4i7amufs56nu372ynrhhep1t9da14j&ep=v1_gifs_search&rid=giphy.gif&ct=g",
          heroid: 16,
        },
        {
          id: 17,
          question: "Quel pays est le plus grand producteur mondial de café ?",
          options: ["Brésil", "Colombie", "Vietnam", "Ethiopie"],
          answer: "Brésil",
          info: "Le Brésil est le pays qui produit le plus de café dans le monde. Une production qui s'élève à 2,68 millions de tonnes par an, ce qui explique que le tiers du café disponible sur le marché mondial est produit par le Brésil.",
          img: "https://brulerie-dalre-shop.com/img/post/21.jpg",
          heroid: 17,
        },
        {
          id: 18,
          question: "Quelle est la capitale du Canada ?",
          options: ["Toronto", "Montréal", "Ottawa", "Vancouver"],
          answer: "Ottawa",
          info: "Sa capitale est Ottawa et ses trois plus grandes régions métropolitaines sont Toronto, Montréal et Vancouver. Les langues officielles du pays sont l'anglais et le français. 40 720 593 habitants.",
          img: "https://upload.wikimedia.org/wikipedia/commons/thumb/c/cf/Flag_of_Canada.svg/1024px-Flag_of_Canada.svg.png",
          heroid: 18,
        },
        {
          id: 19,
          question: "Qui était le premier empereur romain ?",
          options: ["Auguste", "Jules César", "Néron", "Caligula"],
          answer: "Auguste",
          info: "Fils adoptif de Jules César, ce jeune patricien sans expérience se hissa au sommet de l'État. Après avoir rétabli la paix dans la République finissante, il prit le contrôle des institutions et , en 27 avant J. -C, devint Auguste, premier empereur de Rome.",
          img: "https://odysseum.eduscol.education.fr/sites/default/files/2019-12/Auguste%20Prima%20Porta.jpg",
          heroid: 19,
        },
      ],
      expert: [
        {
          id: 20,
          question:
            "Quel est le plus grand désert du monde en termes de superficie ?",
          options: ["Le Sahara", "L'Antarctique", "Le Gobi", "Le Kalahari"],
          answer: "L'Antarctique",
          info: "Techniquement, L'Antartique est considéré comme un désert polaire,il est donc le plus grand avec une superficie de 14 000 000 km²",
          img: "https://images.bfmtv.com/IAu5R-51wshYWdjtdMrRaozxiNI=/0x53:1024x629/1024x0/images/Le-glacier-Union-en-Antarctique-le-14-septembre-2017-photo-d-illustration-1428014.jpg",
          heroid: 20,
        },
        {
          id: 21,
          question: "Qui était le premier président des États-Unis ?",
          options: [
            "Thomas Jefferson",
            "George Washington",
            "John Adams",
            "James Madison",
          ],
          answer: "George Washington",
          info: "Considéré comme l'un des Pères fondateurs des États-Unis par les Américains, George Washington a fait l'objet de nombreux hommages depuis la fin du xviiie siècle : son nom a été donné à la capitale des États-Unis, à un État du nord-ouest de l'Union, ainsi qu'à de nombreux sites et monuments. Son effigie figure depuis 1932 sur la pièce de 25 cents (quarter) ainsi que sur le billet d'un dollar2.",
          img: "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b6/Gilbert_Stuart_Williamstown_Portrait_of_George_Washington.jpg/800px-Gilbert_Stuart_Williamstown_Portrait_of_George_Washington.jpg",
          heroid: 21,
        },
        {
          id: 22,
          question:
            "Qui détient le record du plus grand nombre de buts marqués en une seule saison de Premier League (Angleterre) ?",
          options: [
            "Cristiano Ronaldo",
            "Thierry Henry",
            "Alan Shearer",
            "Andy Cole",
          ],
          answer: "Alan Shearer",
          info: "Alan Shearer, né le 13 août 1970 à Newcastle, est un footballeur international anglais qui évoluait au poste d'attaquant. Considéré comme l'un des meilleurs attaquants de sa génération et l'un des plus grands joueurs de l'histoire de la Premier League, il est le meilleur buteur de la Premier League avec 260 buts.",
          img: "https://i0.wp.com/thesefootballtimes.co/wp-content/uploads/2016/12/shearer.jpg?fit=1600%2C1050&ssl=1",
          heroid: 22,
        },
        {
          id: 23,
          question:
            "Quel réalisateur a remporté le plus grand nombre d'Oscars du meilleur réalisateur ?",
          options: [
            "Steven Spielberg",
            "Alfred Hitchcock",
            "Martin Scorsese",
            "John Ford",
          ],
          answer: "John Ford",
          info: "John Martin Feeney, dit John Ford, est un réalisateur américain, également producteur, né le 1ᵉʳ février 1894 à Cape Elizabeth près de Portland et mort le 31 août 1973 à Palm Desert. John Ford est l'un des réalisateurs américains les plus importants de la période classique de Hollywood.",
          img: "https://t2.gstatic.com/licensed-image?q=tbn:ANd9GcTvGMoo616jmnd-CQgXsXFW2P52nrAU2hUe97YHdzjpHjrtvkhFX36vclxTP2Vveh7t",
          heroid: 23,
        },
        {
          id: 24,
          question:
            "Quel joueur rocket league francais a gagné ses premiers RLCS ?",
          options: ["Zen", "Vatira", "Alpha54", "Kaydop"],
          answer: "Zen",
          info: "Alexis « Zen » Bernier est un jeune joueur professionnel sur Rocket League. Né le 20 février 2007 (16 ans), il fait partie de l'équipe esport Vitality.  Malgré sa faible expérience en compétition de haut niveau, il est considéré par de nombreux experts comme un prodige et l'un des meilleurs au monde sur Rocket League. Depuis le Le 14 mai 2023, Zen avec son équipe Vitality a remporté les 3 regionaux des RLCS européens depuis son arrivée en ligue professionnelle. Le 13 août 2023, Zen avec la Team Vitality devient champion du monde sur Rocket League.",
          img: "https://liquipedia.net/commons/images/thumb/2/2f/RLCS_Spring_Major_2022-23_LAN_Michal_Konkol_zen.jpg/250px-RLCS_Spring_Major_2022-23_LAN_Michal_Konkol_zen.jpg",
          heroid: 24,
        },
        {
          id: 25,
          question:
            "Quelle série télévisée a été créée par les frères Duffer ?",
          options: ["The OA", "Stranger Things", "Dark", "Black Mirror"],
          answer: "Stranger Things",
          info: "Stranger Things est une série télévisée américaine de science-fiction horrifique, créée par les frères Matt et Ross Duffer et diffusée depuis le 15 juillet 2016 sur Netflix. Elle compte en 2022 quatre saisons et trente-quatre épisodes. Une cinquième et dernière saison a été annoncée le 17 février 2022, celle-ci est prévue pour 2024.",
          img: "https://media0.giphy.com/media/l41Y9SKrl3kLVamfC/giphy.gif?cid=ecf05e47kv3k9jpsae8c1mv9aizstsjvvr391k7jq2spsgss&ep=v1_gifs_search&rid=giphy.gif&ct=g",
          heroid: 25,
        },
        {
          id: 26,
          question:
            "Dans quelle ville italienne se trouve la Cité du Vatican ?",
          options: ["Rome", "Florence", "Venise", "Milan"],
          answer: "Rome",
          info: "Le Vatican, en forme longue l'État de la Cité du Vatican est un micro-État européen. Il s'agit du support territorial du Saint-Siège enclavé dans la ville de Rome, capitale de l'Italie. Il comptait officiellement 825 habitants en 2019 sur une superficie totale de 0,439 km2, ce qui en fait le plus petit État au monde, ainsi que le moins peuplé.",
          img: "https://dynamic-media-cdn.tripadvisor.com/media/photo-o/1a/7f/22/5a/caption.jpg?w=500&h=400&s=1",
          heroid: 26,
        },
        {
          id: 27,
          question:
            "Quelle est la plus grande île du monde en termes de superficie ?",
          options: ["Groenland", "Madagascar", "Bornéo", "Nouvelle-Guinée"],
          answer: "Groenland",
          info: "Le Groenland est un pays constitutif du royaume du Danemark et un territoire d'outre-mer associé à l'Union européenne3, situé à l'est de l'archipel Arctique dans le Nord-Est de l'Amérique du Nord, entre la mer de Baffin et le détroit de Davis à l'ouest et la mer du Groenland et l'océan Atlantique à l'est.",
          img: "https://images.radio-canada.ca/q_auto,w_700/v1/ici-info/16x9/groenland-arctique-tasiilaq-copenhague-danemark.jpg",
          heroid: 27,
        },
        {
          id: 28,
          question: "Quel est le streamer francais le plus suivis sur Twitch ?",
          options: ["Squeezie", "Gotaga", "Kamet0", "Aminematue"],
          answer: "Squeezie",
          info: "Lucas Hauchard, dit Squeezie, né le 27 janvier 1996 à Vitry-sur-Seine, est un influenceur, vidéaste web, streamer et entrepreneur français. Il est le youtubeur francophone le plus suivi, comptabilisant en novembre 2023 plus de 18,5 millions d'abonnés. Depuis les années 2010, il propose sur YouTube un contenu divertissant ; et est présent sur Twitch où il compte plus de 4,8 millions d'abonnés.",
          img: "https://img.nrj.fr/-8vEkRNFirKcPTTLyWYXZkuI__U=/medias%2F2022%2F12%2F8oqo9u-nbqs7h6lksrhh1nlmlkbbjjkslxicbzrz4l4_638e17907ddc4.jpg",
          heroid: 28,
        },
        {
          id: 29,
          question:
            "Quel est l'animé dans lequel le personnage principal est Eren",
          options: [
            "Demon slayer",
            "Jujutsu kaisen",
            "L'attaque des titans",
            "One piece",
          ],
          answer: "L'attaque des titans",
          info: "L'Attaque des Titans (進撃の巨人, Shingeki no Kyojin?, litt. Le Géant assaillant, souvent abrégé SnK), aussi connu sous le titre américain Attack on Titan, est un shōnen manga écrit et dessiné par Hajime Isayama.",
          img: "https://media0.giphy.com/media/9SvQFZ5xoGHza/giphy.gif?cid=ecf05e476wdgvy9uhdvxnt4mktzkv3fqir86d738rzt2kb7f&ep=v1_gifs_search&rid=giphy.gif&ct=g",
          heroid: 29,
        },
      ],
    },
  },
];
